# Generated by Django 5.2.7 on 2025-12-23 05:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('niveau', models.CharField(help_text='Niveau du compartiment (haut, milieu, bas)', max_length=50)),
                ('categorie', models.CharField(blank=True, help_text='Catégorie des livres', max_length=100)),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compartiment',
                'verbose_name_plural': 'Compartiments',
                'ordering': ['etagere', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('salle', models.CharField(max_length=50)),
                ('etage', models.IntegerField()),
                ('capacite_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Étagère',
                'verbose_name_plural': 'Étagères',
                'ordering': ['etage', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('date_partenariat', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('biographie', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['nom', 'prenom'],
                'unique_together': {('nom', 'prenom')},
            },
        ),
        migrations.CreateModel(
            name='EmplacementLivre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('code_emplacement', models.CharField(max_length=50, unique=True)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compartiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='bibliothech.compartiment')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
                'ordering': ['compartiment', 'position'],
                'unique_together': {('compartiment', 'position')},
            },
        ),
        migrations.AddField(
            model_name='compartiment',
            name='etagere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartiments', to='bibliothech.etagere'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('faculte', models.CharField(max_length=200)),
                ('departement', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOCTORAT', 'Doctorat')], max_length=10)),
                ('annee_inscription', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='bibliothech.universite')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], max_length=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('nombre_emprunts_max', models.IntegerField(default=5)),
                ('duree_emprunt_jours', models.IntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='bibliothech.etudiant')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='ISBN à 13 chiffres', max_length=13, unique=True)),
                ('titre', models.CharField(max_length=300)),
                ('sous_titre', models.CharField(blank=True, max_length=300)),
                ('editeur', models.CharField(max_length=200)),
                ('annee_publication', models.IntegerField()),
                ('nombre_pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('langue', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('DE', 'Allemand'), ('IT', 'Italien'), ('AR', 'Arabe'), ('OTHER', 'Autre')], default='FR', max_length=10)),
                ('categorie', models.CharField(max_length=100)),
                ('resume', models.TextField(blank=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('nombre_exemplaires', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('MOYEN', 'État moyen'), ('MAUVAIS', 'Mauvais état')], default='BON', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('version_numerique', models.FileField(blank=True, null=True, upload_to='livres_numeriques/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteurs', models.ManyToManyField(related_name='livres', to='bibliothech.auteur')),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='bibliothech.emplacementlivre')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('RAPPEL', 'Rappel de retour'), ('RETARD', 'Retard'), ('RESERVATION', 'Réservation disponible'), ('ABONNEMENT', 'Abonnement')], max_length=15)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bibliothech.etudiant')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('BIBLIOTHECAIRE', 'Bibliothécaire'), ('ASSISTANT', 'Assistant'), ('DIRECTEUR', 'Directeur'), ('TECHNICIEN', 'Technicien')], max_length=20)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='bibliothech.universite')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('PERDU', 'Perdu')], default='EN_COURS', max_length=15)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliothech.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliothech.livre')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprunts_traites', to='bibliothech.personnel')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PRETE', 'Prêt à retirer'), ('ANNULEE', 'Annulée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bibliothech.etudiant')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bibliothech.livre')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='compartiment',
            unique_together={('etagere', 'numero')},
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['isbn'], name='bibliothech_isbn_cfe33a_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['titre'], name='bibliothech_titre_4123f0_idx'),
        ),
        migrations.AddIndex(
            model_name='livre',
            index=models.Index(fields=['categorie'], name='bibliothech_categor_824a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['statut'], name='bibliothech_statut_bca609_idx'),
        ),
        migrations.AddIndex(
            model_name='emprunt',
            index=models.Index(fields=['date_retour_prevue'], name='bibliothech_date_re_95b81d_idx'),
        ),
    ]
