# Generated by Django 5.2.7 on 2025-12-26 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEmprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_emprunt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name="Durée d'emprunt (jours)")),
                ('nombre_emprunts_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name="Nombre maximum d'emprunts")),
                ('nombre_renouvellements', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre de renouvellements autorisés')),
                ('cotisation_annuelle', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cotisation annuelle (€)')),
                ('reduction_amende', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Réduction sur amendes (%)')),
                ('priorite_reservation', models.BooleanField(default=False, verbose_name='Priorité sur les réservations')),
                ('acces_ressources_numeriques', models.BooleanField(default=True, verbose_name='Accès aux ressources numériques')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Catégorie d'emprunteur",
                'verbose_name_plural': "Catégories d'emprunteurs",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(choices=[('BIENVENUE', 'Email de bienvenue'), ('RAPPEL_ECHEANCE', 'Rappel avant échéance'), ('RETARD', 'Notification de retard'), ('RESERVATION_DISPONIBLE', 'Réservation disponible'), ('RENOUVELLEMENT', 'Confirmation de renouvellement'), ('ANNULATION', "Annulation d'emprunt/réservation")], max_length=50, unique=True, verbose_name="Type d'email")),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('corps_message', models.TextField(help_text='Utilisez {nom}, {prenom}, {titre_livre}, {date_retour}, etc. pour personnaliser', verbose_name='Corps du message')),
                ('actif', models.BooleanField(default=True, verbose_name='Email actif')),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configurations emails',
                'ordering': ['type_email'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueParametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametre_modifie', models.CharField(max_length=100, verbose_name='Paramètre modifié')),
                ('ancienne_valeur', models.TextField(verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(verbose_name='Nouvelle valeur')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.CharField(max_length=100, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique des paramètres',
                'verbose_name_plural': 'Historique des paramètres',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du jour férié')),
                ('date', models.DateField(verbose_name='Date')),
                ('recurrent', models.BooleanField(default=True, help_text='Si coché, ce jour sera férié chaque année', verbose_name='Récurrent chaque année')),
                ('fermeture_totale', models.BooleanField(default=True, help_text='Si décoché, horaires réduits', verbose_name='Fermeture totale')),
                ('horaire_ouverture', models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture (si horaires réduits)")),
                ('horaire_fermeture', models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture (si horaires réduits)')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MessageSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type_message', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succès')], default='INFO', max_length=10, verbose_name='Type de message')),
                ('cible', models.CharField(choices=[('TOUS', 'Tous les utilisateurs'), ('ETUDIANTS', 'Étudiants uniquement'), ('PERSONNEL', 'Personnel uniquement')], default='TOUS', max_length=20, verbose_name='Destinataires')),
                ('date_debut', models.DateTimeField(verbose_name="Date de début d'affichage")),
                ('date_fin', models.DateTimeField(verbose_name="Date de fin d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('prioritaire', models.BooleanField(default=False, help_text='Sera affiché en haut de page', verbose_name='Message prioritaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message système',
                'verbose_name_plural': 'Messages système',
                'ordering': ['-prioritaire', '-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ParametreBibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bibliotheque', models.CharField(max_length=200, verbose_name='Nom de la bibliothèque')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bibliotheque/logos/', verbose_name='Logo')),
                ('horaire_ouverture', models.TimeField(default='08:00', verbose_name="Heure d'ouverture")),
                ('horaire_fermeture', models.TimeField(default='18:00', verbose_name='Heure de fermeture')),
                ('jours_fermeture', models.CharField(default='Dimanche', help_text='Séparer par des virgules (ex: Dimanche, Lundi)', max_length=100, verbose_name='Jours de fermeture')),
                ('duree_emprunt_defaut', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name="Durée d'emprunt par défaut (jours)")),
                ('nombre_emprunts_max', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name="Nombre maximum d'emprunts simultanés")),
                ('nombre_renouvellements_max', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nombre maximum de renouvellements')),
                ('amende_par_jour', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amende par jour de retard (€)')),
                ('amende_maximum', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amende maximum (€)')),
                ('delai_suspension_apres_retard', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Délai de suspension après retard (jours)')),
                ('duree_reservation_jours', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name="Durée de validité d'une réservation (jours)")),
                ('nombre_reservations_max', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Nombre maximum de réservations simultanées')),
                ('rappel_avant_echeance', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='Rappel avant échéance (jours)')),
                ('rappel_apres_retard', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Rappel après retard (jours)')),
                ('duree_validite_carte', models.IntegerField(default=365, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(1825)], verbose_name='Durée de validité de la carte (jours)')),
                ('prix_carte', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de la carte de membre (€)')),
                ('age_minimum', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Âge minimum pour s'inscrire")),
                ('activer_notifications_email', models.BooleanField(default=True, verbose_name='Activer les notifications par email')),
                ('activer_notifications_sms', models.BooleanField(default=False, verbose_name='Activer les notifications par SMS')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de la bibliothèque',
                'verbose_name_plural': 'Paramètres de la bibliothèque',
            },
        ),
        migrations.CreateModel(
            name='RegleMetier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique pour identifier la règle', max_length=50, unique=True, verbose_name='Code de la règle')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la règle')),
                ('description', models.TextField(verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Règle active')),
                ('valeur_numerique', models.IntegerField(blank=True, null=True, verbose_name='Valeur numérique')),
                ('valeur_texte', models.CharField(blank=True, max_length=500, null=True, verbose_name='Valeur texte')),
                ('valeur_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valeur booléenne')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle métier',
                'verbose_name_plural': 'Règles métier',
                'ordering': ['code'],
            },
        ),
    ]
