# Generated by Django 5.2.7 on 2026-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0003_alter_etudiant_annee_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='annee_inscription',
            field=models.CharField(max_length=11),
        ),
    ]
