# Generated by Django 5.2.7 on 2026-01-09 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0004_alter_etudiant_annee_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('adresse', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Université',
                'verbose_name_plural': 'Universités',
            },
        ),
        migrations.AddField(
            model_name='emprunt',
            name='remarques',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorieemprunteur',
            name='cotisation_annuelle',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cotisation annuelle (Fbu)'),
        ),
        migrations.CreateModel(
            name='Faculte1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultes', to='bibliothech.universite')),
            ],
            options={
                'verbose_name': 'Faculté',
                'verbose_name_plural': 'Facultés',
                'unique_together': {('code', 'universite')},
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='bibliothech.universite')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='bibliothech.faculte1')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(max_length=50)),
                ('annee_academique', models.CharField(max_length=20)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='bibliothech.departement')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='bibliothech.faculte1')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Etudiant1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, max_length=50, unique=True)),
                ('api_id', models.CharField(blank=True, help_text="ID de l'étudiant dans le système externe", max_length=100, null=True, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=50)),
                ('annee_academique', models.CharField(blank=True, max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé')], default='actif', max_length=20)),
                ('sync_depuis_api', models.BooleanField(default=True, help_text="Indique si l'étudiant provient de l'API")),
                ('derniere_sync', models.DateTimeField(auto_now=True, help_text="Date de dernière synchronisation avec l'API")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('donnees_api_brutes', models.JSONField(blank=True, help_text="Données brutes reçues de l'API", null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants1', to='bibliothech.classe')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants1', to='bibliothech.departement')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants1', to='bibliothech.universite')),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants1', to='bibliothech.faculte1')),
            ],
            options={
                'verbose_name': 'Étudiant (API)',
                'verbose_name_plural': 'Étudiants (API)',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['matricule'], name='bibliothech_matricu_63710e_idx'), models.Index(fields=['email'], name='bibliothech_email_10fa4e_idx'), models.Index(fields=['universite', 'faculte'], name='bibliothech_univers_8e6d2e_idx')],
            },
        ),
    ]
