# Generated by Django 5.2.7 on 2026-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0005_universite1_emprunt_remarques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculte1',
            name='sigle',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
