# Generated by Django 5.2.7 on 2026-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0006_faculte1_sigle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculte1',
            unique_together=set(),
        ),
    ]
