# Generated by Django 5.2.7 on 2026-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0007_alter_faculte1_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='universite',
        ),
        migrations.AddField(
            model_name='departement',
            name='sigle',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
