# Generated by Django 5.2.7 on 2026-01-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0008_remove_departement_universite_departement_sigle'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='universite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='bibliothech.universite'),
        ),
    ]
