# Generated by Django 5.2.7 on 2026-02-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0009_departement_universite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auteur',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auteur',
            name='genre_litteraire',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auteur',
            name='maison_edition_principale',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auteur',
            name='nb_livres_publies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auteur',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='premier_livre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='prix_litteraires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='pseudonyme',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
