# Generated by Django 5.2.7 on 2026-02-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0010_alter_auteur_unique_together_auteur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='date_deces',
            field=models.DateField(blank=True, null=True),
        ),
    ]
