# Generated by Django 5.2.7 on 2026-02-23 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothech', '0011_auteur_date_deces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du type')),
                ('categorie', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant / Chercheur'), ('PERSONNEL', 'Personnel administratif'), ('EXTERNE', 'Membre externe'), ('VIP', 'VIP / Partenaire')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_jours', models.PositiveIntegerField(default=365, help_text="Durée de validité de l'abonnement en jours", verbose_name='Durée (jours)')),
                ('nb_emprunts_max', models.PositiveIntegerField(default=3, verbose_name="Nombre max d'emprunts simultanés")),
                ('duree_emprunt_jours', models.PositiveIntegerField(default=14, verbose_name='Durée max par emprunt (jours)')),
                ('acces_numerique', models.BooleanField(default=False, verbose_name='Accès aux ressources numériques')),
                ('acces_salle_lecture', models.BooleanField(default=True, verbose_name='Accès salle de lecture')),
                ('reservation_possible', models.BooleanField(default=True, verbose_name='Réservation de documents autorisée')),
                ('tarif_annuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tarif annuel (FC ou devise locale)')),
                ('gratuit', models.BooleanField(default=False, verbose_name='Abonnement gratuit')),
                ('actif', models.BooleanField(default=True, verbose_name='Type actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'abonnement",
                'verbose_name_plural': "Types d'abonnement",
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_abonne', models.CharField(help_text='Identifiant unique généré automatiquement ou saisi manuellement', max_length=20, unique=True, verbose_name="Numéro d'abonné")),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre / Non précisé')], default='A', max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=80, verbose_name='Nationalité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='abonnes/photos/', verbose_name='Photo de profil')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{7,20}$', 'Numéro de téléphone invalide.')], verbose_name='Téléphone')),
                ('telephone_alt', models.CharField(blank=True, max_length=20, verbose_name='Téléphone alternatif')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse postale')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, default='RDC', max_length=80, verbose_name='Pays')),
                ('faculte', models.CharField(blank=True, max_length=150, verbose_name='Faculté / Département')),
                ('niveau_etude', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('DOC', 'Doctorat'), ('POST_DOC', 'Post-doctorat'), ('AUTRE', 'Autre'), ('NA', 'Non applicable')], default='NA', max_length=10, verbose_name="Niveau d'étude")),
                ('numero_etudiant', models.CharField(blank=True, max_length=50, verbose_name='Numéro étudiant / matricule académique')),
                ('profession', models.CharField(blank=True, max_length=150, verbose_name='Profession / Fonction')),
                ('type_piece', models.CharField(blank=True, choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport'), ('PERMIS', 'Permis de conduire'), ('CARTE_ETU', 'Carte étudiante'), ('AUTRE', 'Autre')], max_length=15, verbose_name="Type de pièce d'identité")),
                ('numero_piece', models.CharField(blank=True, max_length=80, verbose_name='Numéro de pièce')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='abonnes/pieces/', verbose_name='Copie de la pièce (scan/photo)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('EN_ATTENTE', 'En attente de validation')], default='EN_ATTENTE', max_length=15, verbose_name="Statut de l'abonnement")),
                ('date_inscription', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name="Date de début de l'abonnement")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('renouvellement_auto', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date du dernier paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('exonere', models.BooleanField(default=False, help_text="Cocher si l'abonné bénéficie d'une exemption de paiement", verbose_name='Exonéré(e) de cotisation')),
                ('motif_exoneration', models.CharField(blank=True, max_length=255, verbose_name="Motif de l'exonération")),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('universite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnes', to='bibliothech.universite', verbose_name='Université / Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonne', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonnes_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par (personnel)')),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnes', to='bibliothech.typeabonnement', verbose_name="Type d'abonnement")),
            ],
            options={
                'verbose_name': 'Abonné(e)',
                'verbose_name_plural': 'Abonné(e)s',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['numero_abonne'], name='bibliothech_numero__27a7a1_idx'), models.Index(fields=['statut'], name='bibliothech_statut_65f62e_idx'), models.Index(fields=['date_expiration'], name='bibliothech_date_ex_1bceed_idx')],
            },
        ),
    ]
